using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace Rx3.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ReactiveCommandGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: TransformCandidate);
        context.RegisterSourceOutput(candidates, GenerateCode);
    }

    private static (string fullTypeName, string ns, string methodName, string hint)? TransformCandidate(
        GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        if (ctx.Node is not MethodDeclarationSyntax methodDecl) return null;
        if (!HasAttribute(methodDecl.AttributeLists, "ReactiveCommand", ctx.SemanticModel, ct)) return null;

        var typeDecl = methodDecl.FirstAncestorOrSelf<TypeDeclarationSyntax>();
        if (typeDecl is null) return null;
        var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(typeDecl, ct) as ITypeSymbol;
        if (typeSymbol is null || !InheritsFrom(typeSymbol, "Rx3.ReactiveObject")) return null;

        var fullTypeName = typeDecl.Identifier.Text;
        for (var outer = typeDecl.Parent; outer is TypeDeclarationSyntax ot; outer = ot.Parent)
            fullTypeName = $"{ot.Identifier.Text}.{fullTypeName}";

        return (fullTypeName, typeSymbol.ContainingNamespace?.ToDisplayString() ?? "",
            methodDecl.Identifier.Text,
            $"{fullTypeName.Replace('.', '_')}.{methodDecl.Identifier.Text}Command.g.cs");
    }

    private static void GenerateCode(SourceProductionContext ctx,
        (string fullTypeName, string ns, string methodName, string hint)? data)
    {
        if (data is null) return;
        var (fullTypeName, ns, methodName, hint) = data.Value;
        var cmd = $"{methodName}Command";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using R3;");
        if (!string.IsNullOrEmpty(ns)) sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        foreach (var part in fullTypeName.Split('.'))
        {
            sb.AppendLine($"partial class {part}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    private ReactiveCommand? _{cmd};");
        sb.AppendLine($"    public ReactiveCommand {cmd}");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (_{cmd} is null)");
        sb.AppendLine("            {");
        sb.AppendLine($"                var canExecute = new BehaviorSubject<bool>(true);");
        sb.AppendLine($"                _{cmd} = canExecute.ToReactiveCommand(_ => {methodName}());");
        sb.AppendLine("            }");
        sb.AppendLine($"            return _{cmd};");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public Observable<Unit> When{methodName}() => {cmd};");

        foreach (var _ in fullTypeName.Split('.'))
            sb.AppendLine("}");

        ctx.AddSource(hint, sb.ToString());
    }

    private static bool HasAttribute(SyntaxList<AttributeListSyntax> attrLists, string name,
        SemanticModel semModel, System.Threading.CancellationToken ct)
    {
        foreach (var list in attrLists)
            foreach (var attr in list.Attributes)
            {
                if (semModel.GetTypeInfo(attr, ct).Type?.ToDisplayString() is string tn &&
                    (tn.EndsWith($".{name}Attribute") || tn == name)) return true;
                if (attr.Name.ToString() is string ns && (ns == name || ns == $"{name}Attribute")) return true;
            }
        return false;
    }

    private static bool InheritsFrom(ITypeSymbol? type, string baseType)
    {
        while (type is not null) { if (type.ToDisplayString() == baseType) return true; type = type.BaseType; }
        return false;
    }
}
