using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace Rx3.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class ReactivePropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register a debug marker to verify the generator runs
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("debug_marker.g.cs", "// Rx3.SourceGenerator: ReactivePropertyGenerator loaded");
        });

        // Find all partial property declarations and field declarations,
        // then check if they have [Reactive] via semantic model
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) =>
            {
                // Match: partial properties and fields
                if (node is PropertyDeclarationSyntax propDecl &&
                    propDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                    return true;

                if (node is FieldDeclarationSyntax fieldDecl)
                    return true;

                return false;
            },
            transform: TransformCandidate);

        context.RegisterSourceOutput(candidates, GenerateCode);
    }

    private static (string? typeName, string? ns, string propName, string fieldName, string propType, string hint)? TransformCandidate(
        GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var semModel = ctx.SemanticModel;
        var node = ctx.Node;

        // Check for [Reactive] attribute
        bool hasReactive = false;
        string propName = "", fieldName = "", propType = "";
        TypeDeclarationSyntax? typeDecl = null;

        if (node is PropertyDeclarationSyntax propDecl)
        {
            hasReactive = HasAttribute(propDecl.AttributeLists, "Reactive", semModel, ct);
            if (!hasReactive) return null;

            typeDecl = propDecl.FirstAncestorOrSelf<TypeDeclarationSyntax>();
            if (typeDecl is null) return null;

            propName = propDecl.Identifier.Text;
            fieldName = $"_{char.ToLowerInvariant(propName[0])}{propName.Substring(1)}";
            propType = propDecl.Type.ToString();
        }
        else if (node is FieldDeclarationSyntax fieldDecl)
        {
            hasReactive = HasAttribute(fieldDecl.AttributeLists, "Reactive", semModel, ct);
            if (!hasReactive) return null;

            typeDecl = fieldDecl.FirstAncestorOrSelf<TypeDeclarationSyntax>();
            if (typeDecl is null) return null;

            var varDecl = fieldDecl.Declaration.Variables.FirstOrDefault();
            if (varDecl is null) return null;

            fieldName = varDecl.Identifier.Text;
            propName = ToPropertyName(fieldName);
            propType = fieldDecl.Declaration.Type.ToString();
        }
        else
        {
            return null;
        }

        // Verify class extends ReactiveObject
        var typeSymbol = semModel.GetDeclaredSymbol(typeDecl, ct) as ITypeSymbol;
        if (typeSymbol is null) return null;
        if (!InheritsFrom(typeSymbol, "Rx3.ReactiveObject")) return null;

        // Build full type name including nesting
        var fullTypeName = typeDecl.Identifier.Text;
        var outer = typeDecl.Parent;
        while (outer is TypeDeclarationSyntax outerType)
        {
            fullTypeName = $"{outerType.Identifier.Text}.{fullTypeName}";
            outer = outerType.Parent;
        }

        var ns = typeSymbol.ContainingNamespace?.ToDisplayString() ?? "";
        var hint = $"{fullTypeName.Replace('.', '_')}.{propName}.g.cs";

        return (fullTypeName, ns, propName, fieldName, propType, hint);
    }

    private static void GenerateCode(SourceProductionContext context,
        (string? typeName, string? ns, string propName, string fieldName, string propType, string hint)? data)
    {
        if (data is null) return;
        var (typeName, ns, propName, fieldName, propType, hint) = data.Value;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        // Handle nested types: "Outer.Inner" -> need nested partial classes
        var typeParts = typeName.Split('.');
        foreach (var part in typeParts)
        {
            sb.AppendLine($"partial class {part}");
            sb.AppendLine("{");
        }
        // Track closing braces
        sb.AppendLine($"    private {propType} {fieldName};");
        sb.AppendLine();
        sb.AppendLine($"    public partial {propType} {propName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {fieldName};");
        sb.AppendLine($"        set => SetProperty(ref {fieldName}, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public global::R3.Observable<{propType}> When{propName}Changed()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return WhenValueChanged(() => {propName});");
        sb.AppendLine("    }");

        // Close nested type braces
        for (int i = 0; i < typeParts.Length; i++)
            sb.AppendLine("}");

        context.AddSource(hint, sb.ToString());
    }

    private static bool HasAttribute(SyntaxList<AttributeListSyntax> attrLists, string name,
        SemanticModel semModel, System.Threading.CancellationToken ct)
    {
        foreach (var list in attrLists)
        {
            foreach (var attr in list.Attributes)
            {
                var typeInfo = semModel.GetTypeInfo(attr, ct);
                var typeName = typeInfo.Type?.ToDisplayString() ?? "";
                if (typeName.EndsWith($".{name}Attribute") || typeName == name)
                    return true;

                var nameStr = attr.Name.ToString();
                if (nameStr == name || nameStr == $"{name}Attribute")
                    return true;
            }
        }
        return false;
    }

    private static bool InheritsFrom(ITypeSymbol? type, string baseTypeFullName)
    {
        while (type is not null)
        {
            if (type.ToDisplayString() == baseTypeFullName)
                return true;
            type = type.BaseType;
        }
        return false;
    }

    private static string ToPropertyName(string fieldName)
    {
        var name = fieldName;
        if (name.StartsWith("_"))
            name = name.Substring(1);
        else if (name.StartsWith("m_"))
            name = name.Substring(2);
        if (name.Length > 0)
            name = char.ToUpperInvariant(name[0]) + name.Substring(1);
        return name;
    }
}
